name: Tests
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v1
        with:
          node-version: 20
      - uses: actions/cache@v3
        with:
          path: ~/.npm
          key: v1/${{ runner.os }}/node-14/${{ hashFiles('**/package-lock.lock') }}
          restore-keys: v1/${{ runner.os }}/node-14/
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
        env:
          PERCY_TOKEN: 213fd7baaa45add195c29682c46346eaf8f283bfa7cd82cb4131ca3c81469a3e
